<a href="https://colab.research.google.com/github/viveksharma-niet/LogisticRegressionUpgrade/blob/main/SMS_Spam_Ham_Classifier_Multinomial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
import pandas as pd

smsdata = pd.read_table('https://raw.githubusercontent.com/viveksharma-niet/LogisticRegressionUpgrade/refs/heads/main/smsspamcollection.csv', sep='^([^,]+),',
    engine='python',header=None, names=['Class', 'sms'], encoding="utf-8" )
smsdata.head()

Class                                                sms
NaN  ham  "Go until jurong point, crazy.. Available only...
NaN   ham                      Ok lar... Joking wif u oni...
NaN  spam  Free entry in 2 a wkly comp to win FA Cup fina...
NaN   ham  U dun say so early hor... U c already then say...
NaN   ham  "Nah I don't think he goes to usf, he lives ar...

In [43]:
smsdata = smsdata[(smsdata.Class =='ham') | ( smsdata.Class =='spam') ]

In [47]:
from sklearn.model_selection import train_test_split

smsdata['label'] = smsdata.Class.map({'ham':0, 'spam':1})
smsdata.head()

Class                                                sms  label
NaN   ham                      Ok lar... Joking wif u oni...      0
NaN  spam  Free entry in 2 a wkly comp to win FA Cup fina...      1
NaN   ham  U dun say so early hor... U c already then say...      0
NaN   ham  "Nah I don't think he goes to usf, he lives ar...      0
NaN  spam  "FreeMsg Hey there darling it's been 3 week's ...      1

In [51]:
X = smsdata.sms
y = smsdata.label
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, test_size=0.3, random_state=100)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(3901,)
(3901,)
(1672,)
(1672,)


In [52]:
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer(stop_words='english')
vec.fit(X_train)


CountVectorizer(stop_words='english')

In [53]:
X_train_tranformed = vec.transform(X_train)
X_test_tranformed = vec.transform(X_test)

In [56]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X_train_tranformed, y_train)


print(mnb.predict(X_test_tranformed))
print(mnb.predict_proba(X_test_tranformed))


[0 0 0 ... 0 0 0]
[[8.04904778e-01 1.95095222e-01]
 [1.00000000e+00 1.64586205e-11]
 [9.99993721e-01 6.27942639e-06]
 ...
 [9.78968410e-01 2.10315903e-02]
 [9.95317391e-01 4.68260867e-03]
 [9.99999996e-01 4.02103118e-09]]


In [57]:
y_test_pred = mnb.predict_proba(X_test_tranformed)

In [58]:
y_pred_class = mnb.predict(X_test_tranformed)

In [59]:
from sklearn import metrics

In [60]:
metrics.accuracy_score(y_test, y_pred_class)

0.9856459330143541

In [61]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[1463,   10],
       [  14,  185]])

In [63]:
metrics.precision_score(y_test, y_pred_class)

0.9487179487179487